chore(lazy-loading): initialize lazy-loading example
TheDutchCoder/webpack-guides-code-examples pull request #19
Opened 2017-07-19 03:35 UTC by skipjack

Also had this one sitting around. Pretty sure it does line up with the finalized _Lazy Loading_ guide. If you see any discrepancies, let me know.

2017-07-19 12:30 UTC, TheDutchCoder requested changes
Add the missing semicolons and I'll merge this in. We can alter the examples in another PR later on, if they're not aligned with the Guides yet/anymore.

2017-07-19 12:30 UTC, TheDutchCoder commented on examples/lazy-loading/src/index.js
> +    })
Missing ;

2017-07-19 12:30 UTC, TheDutchCoder commented on examples/lazy-loading/src/print.js
> +}
Missing ;

2017-07-19 22:36 UTC, skipjack commented
@TheDutchCoder updated. Side note: this is an example where "Squash and Merge" would be perfect to get rid of all those "... semicolon" commits. They would just create noise on master and aren't very helpful to have in the history.

2017-07-24 12:44 UTC, TheDutchCoder commented
Gotcha!

2017-07-24 12:45 UTC, merged